Add test for AutoSave
apache/jackrabbit-filevault pull request #241
Opened 2022-08-03 17:30 UTC by kwin

Verify that counters behave correctly

2022-08-04 16:43 UTC, reschke approved these changes

2022-08-04 17:40 UTC, reschke requested changes
I'm not sure why but it seems that in my test, it now saves after 1024 nodes, then 2048 nodes, and then is back to a threshold of 1.

2022-08-04 18:02 UTC, kwin commented
> ... back to a threshold of 1.

This should be fixed now in https://github.com/apache/jackrabbit-filevault/pull/241/commits/4d4407c8b774a0be9b2119937acc2a318eb5e50e

Still the save() won't recover in that case, i.e. the package install won't succeed.

2022-08-05 06:45 UTC, reschke approved these changes

2022-08-05 07:10 UTC, merged